通常弾、チャージショットの実装／描画 #23
Takuto-Miyoshi/Team_PvPShooting pull request #24
Opened 2020-12-17 01:04 UTC by yodai-toda

通常弾とチャージショットを向いている方向の画像で描画
弾とプレイヤーの当たり判定を修正

2020-12-21 03:04 UTC, Takuto-Miyoshi requested changes
はい。

2020-12-21 03:04 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/GameScene.cpp
>  					//--------------------------------------------------------------------------
当たり判定が若干ガバガバです。
[仕様書](https://docs.google.com/spreadsheets/d/1uwlGH41toRJdwax7RjDAFGntxzUCfIzkLTbulNmmbCQ/edit#gid=1490184943&range=B213)を参考にしてください。
ナポレオンはいいのですが、信長の弾の判定は矩形です。

2020-12-21 03:04 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
>  					chargeCount = 0;
射撃のクールタイムが消えています。
`shootingCoolTime = 0;`を消したのが原因かと思います。

2020-12-21 03:04 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Bullet.cpp
> +	}
三項演算子を使えばコンパクトになるのではないでしょうか。
好みの問題かもしれませんが。

2020-12-23 06:39 UTC, yodai-toda commented
64b61b5
３つとも修正しました。

2020-12-26 02:19 UTC, Takuto-Miyoshi approved these changes
確認しました。

2020-12-28 02:37 UTC, merged