エフェクトの実装 #25
Takuto-Miyoshi/Team_PvPShooting pull request #26
Opened 2020-12-21 02:28 UTC by yodai-toda

ヒットエフェクト
* ダメージを受けた瞬間、キャラの中心に三枚のヒットエフェクトの画像を0.1秒間隔で描画する

チャージエフェクト
* 1秒以上チャージされている場合は、3枚の画像を0.1秒間隔で描画し、チャージショットが撃たれるまで描画を続ける

2020-12-30 19:38 UTC, Takuto-Miyoshi requested changes
確認してみてください。

2020-12-30 19:38 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
`FRAME_RATE`ではなく`CHARGE_COUNT`ではないですか？

2020-12-31 09:35 UTC, yodai-toda commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
1秒待ってから描画開始だったので、1秒がわかりやすいようにと思って`FRAME_RATE`を使ってました。
でも言われてみれば`CHARGE_COUNT`のほうが適切な気がしたので、 7b2fe87 で修正しました。

2020-12-31 21:42 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
チャージエフェクトを表示するタイミングが`CHARGE_COUNT / 2`だと、まだチャージが完了してないようなのですが・・・
チャージエフェクトが表示された瞬間にボタンを離して確認してみてください。

2021-01-01 07:26 UTC, yodai-toda commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
[仕様書](https://docs.google.com/spreadsheets/d/1uwlGH41toRJdwax7RjDAFGntxzUCfIzkLTbulNmmbCQ/edit#gid=1490184943)には

> ✕ボタンを押して1秒経過時点でキャラにチャージエフェクトが出現する
> 3枚の画像を0.1秒間隔で連続再生し、チャージショットが撃たれるまでループする

と書かれているので、そうしました。

2021-01-01 11:52 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
プランナーに確認したら仕様書が間違っていたらしく、「チャージが完了したらエフェクトを表示する」ようにしてほしいそうです。

2021-01-01 11:53 UTC, yodai-toda commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +	if( chargeCount >= FRAME_RATE ) {
わかりました

2021-01-01 23:04 UTC, Takuto-Miyoshi approved these changes
確認しました

2021-01-02 14:56 UTC, merged