キャラクター周りの編集 #5
Takuto-Miyoshi/Team_PvPShooting pull request #6
Opened 2020-12-01 15:00 UTC by yodai-toda

* 射撃方向の追加
  * 方向のenumに斜め方向を追加する
  * 上＋右など２方向のキーを同時しているときに斜め方向になる

* 弾の当たり判定の変更
  * 弾の判定を円形にする
  * 当たり判定の大きさを64px×64pxに変更
    * それに伴いテスト用の弾画像の大きさも変更しておく
  * 毎フレーム0.4f 移動する

* 無敵時間の追加
  * ダメージを受けると１秒間無敵になる
    * 攻撃を受けなくなる
    * 無敵の間は0.2秒間隔で点滅する

* その他変更点
  * キャラクターの移動速度を毎フレーム0.2f に変更する

2020-12-05 12:53 UTC, Takuto-Miyoshi requested changes
細かいところだけです。

2020-12-05 12:53 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Header/GameScene.h
> +	bool collision(int L, int R, int T, int B, int x, int y, int radius);
関数はパスカルケースで書いてください。
また、引数は変数にあたる~~はず~~なのでキャメルケースで書いてください。

既存の関数の引数に一部パスカルケースで書いているものがありますが、こちらのミスなので修正しておきます。~~これを見て気づいたので・・・~~

2020-12-05 12:53 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/GameScene.cpp
> +}
ファイルの最終行は改行して空白の行を作ってください。
コンパイルエラーになる可能性があります。
GitHub, SourceTreeで最終行に `No newline at end of file` と表示されていた時は「最終行が改行されてないよ！」ということです。

2020-12-05 12:53 UTC, Takuto-Miyoshi commented on PvP_Shooting/PvP_Shooting/Script/Player.cpp
> +		if( invincibleCount >= 12 && invincibleCount < 24 || invincibleCount >= 36 && invincibleCount <48 ) {
細かいですが `invicibleCount <48` だけ比較演算子の右にスペースがないのが違和感です。

2020-12-05 16:41 UTC, yodai-toda commented
@Takuto-Miyoshi 
e9e9594 で3つとも修正

2つ目の指摘の `No newline at end of file` の存在を知らなかった。
以後、気を付けます。

2020-12-06 08:58 UTC, Takuto-Miyoshi approved these changes
確認しました。
整理してください。

2020-12-07 12:50 UTC, merged